-- SQL schema for MySQL
CREATE DATABASE IF NOT EXISTS pimdb;
USE pimdb;

CREATE TABLE IF NOT EXISTS materias (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  professor VARCHAR(255),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  materiaId INT NOT NULL,
  alunoId VARCHAR(255) NOT NULL,
  np1 DECIMAL(5,2),
  np2 DECIMAL(5,2),
  pim DECIMAL(5,2),
  media DECIMAL(5,2),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (materiaId) REFERENCES materias(id) ON DELETE CASCADE
);
